#version 460
#extension GL_GOOGLE_include_directive : require
#extension GL_EXT_buffer_reference2 : require
#extension GL_EXT_shader_explicit_arithmetic_types_int64 : require

#define THREADBLOCK_SIZE 256

#include "ray.glsl"
#include "bufferReferences.glsl"

layout(push_constant) uniform PushConstants {
    uint64_t outputResultAddr;
    uint64_t indexToPixelAddr;
    uint64_t inPixelAddr;
    uint64_t outPixelAddr;
    uint numberOfRays;
    uint replace;
} pc;

// Occlusion
layout(local_size_x = THREADBLOCK_SIZE) in;
void main() {
    const uint taskIndex = gl_GlobalInvocationID.x;

    RayResultBufferRO outputResults = RayResultBufferRO(pc.outputResultAddr);
    IntBufferRO indexToPixel = IntBufferRO(pc.indexToPixelAddr);
    Vec4BufferRO inPixels = Vec4BufferRO(pc.inPixelAddr);
    Vec4BufferRW outPixels = Vec4BufferRW(pc.outPixelAddr);

    if (taskIndex < pc.numberOfRays) {

        // Pixel.
        int pixel = indexToPixel.data[taskIndex];

        // Color.
        vec3 color = vec3(inPixels.data[pixel]);

        // Shadow factor.
        RayResult outputResult = outputResults.data[taskIndex];
        float shadow = (outputResult.primitiveId == -1) ? 1.0f : 0.0f;

        // Update color.
        if (pc.replace != 0) outPixels.data[pixel] = vec4(color * shadow, 1.0f);
        else outPixels.data[pixel] += vec4(color * shadow, 1.0f);

    }

}
