#version 460
#extension GL_GOOGLE_include_directive : require
#extension GL_EXT_buffer_reference2 : require
#extension GL_EXT_shader_explicit_arithmetic_types_int64 : require
#extension GL_KHR_shader_subgroup_arithmetic : require
#extension GL_KHR_shader_subgroup_ballot : require
#extension GL_EXT_nonuniform_qualifier : require

#define THREADBLOCK_SIZE 256

#include "ray.glsl"
#include "geometrytypes.glsl"
#include "bufferReferences.glsl"
#include "sample.glsl"
#include "pbr.glsl"

#define MAX_FLOAT (3.402823466e+38f)
#define BACKGROUND_COLOR vec3(0.529f, 0.808f, 0.98f)

layout(set = 0, binding = 0) uniform sampler2D textures[];

layout(push_constant) uniform PushConstants {
    uint64_t inputRayAddr;
    uint64_t inputResultAddr;
    uint64_t inputIdxToPixelAddr;

    uint64_t pixelAddr;
    uint64_t decreaseAddr;
    uint64_t seedAddr;
    uint64_t geometryNodeAddr;

    uint64_t shadowRayAddr;
    uint64_t shadowIdxToPixelAddr;

    uint64_t pathRayAddr;
    uint64_t pathIdxToPixelAddr;

    uint64_t counterAddr;

    vec3 light;
    float lightRadius;

    uint russianRoulette;
    uint numberOfRays;
} pc;

// Shading & Generate next bounce's rays
layout(local_size_x = THREADBLOCK_SIZE) in;
void main() {
    const uint taskIndex = gl_GlobalInvocationID.x;

    // Buffer references.
    RayBufferRO inputRays = RayBufferRO(pc.inputRayAddr);
    RayResultBufferRO inputResults = RayResultBufferRO(pc.inputResultAddr);
    IntBufferRO inputIndexToPixel = IntBufferRO(pc.inputIdxToPixelAddr);

    Vec4BufferRO pixels = Vec4BufferRO(pc.pixelAddr);
    Vec4BufferRW decreases = Vec4BufferRW(pc.decreaseAddr);
    UintBufferRW seeds = UintBufferRW(pc.seedAddr);
    GeometryNodeBuffer geometryNodes = GeometryNodeBuffer(pc.geometryNodeAddr);

    // Only active tasks
    if (taskIndex < pc.numberOfRays) {
        int pixel = inputIndexToPixel.data[taskIndex];
        vec3 decrease = decreases.data[pixel].xyz;
        RayResult inputResult = inputResults.data[taskIndex];
        Ray inputRay = inputRays.data[taskIndex];
        uint seed = seeds.data[taskIndex];

        // Color.
        vec3 color = vec3(0.0f);

        // Shadow ray (default: invalid ray).
        Ray shadowRay;
        shadowRay.origin = vec3(0.0f);
        shadowRay.direction = vec3(1.0f, 0.0f, 0.0f);
        shadowRay.tmin = 0.0f;
        shadowRay.tmax = -1.0f;

        // Path ray.
        Ray pathRay;
        bool generatePathRay = false;
        vec3 weight = vec3(1.0f);

        // Triangle index.
        int primitiveId = inputResult.primitiveId;

        // Miss.
        if (primitiveId == -1) {
            color += decrease * BACKGROUND_COLOR;
        }

        // Hit.
        else {
            
            // Fetch hit.
            GeometryNode geometryNode = geometryNodes.data[inputResult.geometryId];
            Triangle tri = unpackTriangle(primitiveId, 
                                          geometryNode.vertexBufferDeviceAddress, 
                                          geometryNode.indexBufferDeviceAddress, 
                                          unpackUnorm2x16(inputResult.packedBary));
            
            // Base color (albedo).
            if (nonuniformEXT(geometryNode.textureIndexBaseColor) > -1) {
		        tri.color.rgb = pow(texture(textures[nonuniformEXT(geometryNode.textureIndexBaseColor)], tri.uv).rgb, vec3(2.2f));
	        }
            tri.color *= geometryNode.baseColorFactor;

            // Normal
            tri.normal = faceforward(tri.normal, inputRay.direction, tri.normal);
            if (nonuniformEXT(geometryNode.textureIndexNormal) > -1) {
		        tri.normal = CalculateNormal(textures[nonuniformEXT(geometryNode.textureIndexNormal)], tri.normal, tri.uv, tri.tangent);
	        }

            // AO, roughness, metallic.
            vec3 aoRoughnessMetallic = vec3(1.0f);
	        if (nonuniformEXT(geometryNode.textureIndexMetallicRoughness) > -1) {
		        aoRoughnessMetallic = texture(textures[nonuniformEXT(geometryNode.textureIndexMetallicRoughness)], tri.uv).rgb;
	        }
	        aoRoughnessMetallic *= vec3(1.0f, geometryNode.roughnessFactor, geometryNode.metallicFactor);

            // Emission.
            if (nonuniformEXT(geometryNode.textureIndexEmissive) > -1){
		        color += texture(textures[nonuniformEXT(geometryNode.textureIndexEmissive)], tri.uv).rgb;
	        }

            // Hit position.
            vec3 hitPos = inputRay.origin + inputRay.direction * inputResult.t;

            // Pick random offset.
            uint hashA = seed + taskIndex;
            uint hashB = 0x9e3779b9u;
            uint hashC = 0x9e3779b9u;
            jenkinsMix(hashA, hashB, hashC);
            vec3 offset = vec3(float(hashA) * exp2(-32.0f), float(hashB) * exp2(-32.0f), float(hashC) * exp2(-32.0f));
            
            // Sample light.
            vec3 lightPos = vec3(0.0f, 0.0f, 0.5f);
            lightPos = fract(lightPos + offset); // Cranley-Patterson
            lightPos = 2.0f * lightPos - 1.0f; // [-1,1]
            vec3 lightDir = (pc.light + pc.lightRadius * lightPos) - hitPos;
            float lightLength = max(length(lightDir), 0.01f);
            lightDir /= lightLength;
            
            // Direct shading.
            float NdotL = max(dot(tri.normal, lightDir), 0.0f);
            float NdotV = max(dot(tri.normal, -inputRay.direction), 0.0f);
            vec3 H = normalize(lightDir - inputRay.direction);

            vec3 F0 = mix(vec3(0.04f), tri.color.rgb, aoRoughnessMetallic.b);
            vec3 F = FresnelSchlick(max(dot(H, -inputRay.direction), 0.0f), F0);

            vec3 specular = ( DistributionGGX(tri.normal, H, aoRoughnessMetallic.g)
									* GeometrySmith(NdotL, NdotV, aoRoughnessMetallic.g) * F)
									/ max(4.0f * NdotL * NdotV, 1.0e-3f);
            vec3 kD = vec3(1.0f) - F;	// kS = F
			kD *= 1.0f - aoRoughnessMetallic.b;
            kD *= tri.color.rgb;

            const float lightIntensity = 100.0f;
            float attenuation = 1.0f / (1.0f + 0.1f * lightLength * lightLength);

            color += decrease * lightIntensity * attenuation * (kD / M_PI + specular) * NdotL;

            // Generate shadow ray.
            const float EPSILON = 1.0e-3f;
            shadowRay.direction = lightDir;
            shadowRay.origin = hitPos + tri.normal * EPSILON;
            shadowRay.tmin = EPSILON;
            shadowRay.tmax = lightLength;

            // Generate path ray.
            if(pc.pathRayAddr > 0) {
                // Probabilities.
                float pd = max(max(kD.x, kD.y), kD.z);
                float ps = max(max(F.x, F.y), F.z);

                // Material scale.
                if(pd + ps > 1.0f) {
                    float s = 1.0f / (pd + ps);
                    kD *= s;
                    F *= s;
                    pd *= s;
                    ps *= s;
                }

                // Generate random numbers.
                float r0 = randf(seed);
                float r1 = randf(seed);
                float r2 = randf(seed);

                // Russian roulette off => normalize probabilities.
                if (pc.russianRoulette == 0) {
                    float s = 1.0f / (pd + ps);
                    pd *= s;
                    ps *= s;
                }

                 if (r2 <= pd + ps) {
                    pathRay.origin = hitPos + tri.normal * EPSILON;
                    pathRay.tmin = EPSILON;
                    pathRay.tmax = MAX_FLOAT;

                    // Glossy distributed ray.
                    if(r2 >= pd) {
                        H = sampleGGX(r0, r1, tri.normal, aoRoughnessMetallic.g);
                        pathRay.direction = reflect(inputRay.direction, H);
                        weight = F / (pd + ps);
                    }
                    // Cosine distributed ray.
                    else {
                        pathRay.direction = cosineRandomVector(r0, r1, tri.normal);
                        weight = kD / (pd + ps);
                    }

                    generatePathRay = true;
                 }

                // Save seed.
                seeds.data[taskIndex] = seed;
            }
        }

        // Update color.
        pixels.data[pixel] = vec4(color, 1.0f);

        // Write shadow rays.
        if (pc.shadowRayAddr > 0) {
            RayBufferWO shadowRays = RayBufferWO(pc.shadowRayAddr);
            IntBufferWO shadowIndexToPixel = IntBufferWO(pc.shadowIdxToPixelAddr);

            shadowRays.data[taskIndex] = shadowRay;
            shadowIndexToPixel.data[taskIndex] = pixel;
        }

        // Write path rays.
        if(pc.pathRayAddr > 0) {
            Counter counter = Counter(pc.counterAddr);
            RayBufferWO pathRays = RayBufferWO(pc.pathRayAddr);
            IntBufferWO pathIndexToPixel = IntBufferWO(pc.pathIdxToPixelAddr);

            uvec4 ballot = subgroupBallot(generatePathRay);
            uint numRays = subgroupBallotBitCount(ballot);
            uint rayOffset = subgroupBallotExclusiveBitCount(ballot);

            uint subgroupOffset = 0;
            if (subgroupElect() && numRays > 0) {
                subgroupOffset = atomicAdd(counter.data, numRays);
            }

            uint rayIndex = subgroupBroadcastFirst(subgroupOffset) + rayOffset;

            if (generatePathRay) {
                RayBufferWO pathRays = RayBufferWO(pc.pathRayAddr);
                IntBufferWO pathIndexToPixel = IntBufferWO(pc.pathIdxToPixelAddr);

                pathRays.data[rayIndex] = pathRay;
                pathIndexToPixel.data[rayIndex] = pixel;
                decreases.data[pixel] *= vec4(weight, 1.0f);
            }
        }
    }
    
}
