#version 460
#extension GL_GOOGLE_include_directive : require
#extension GL_EXT_buffer_reference2 : require
#extension GL_EXT_shader_explicit_arithmetic_types_int64 : require

#define THREADBLOCK_SIZE 256

#include "ray.glsl"
#include "bufferReferences.glsl"

layout(push_constant) uniform PushConstants {
    uint64_t rayIndexAddr;
    uint64_t inRayAddr;
    uint64_t outRayAddr;
    uint64_t inIndexToPixelAddr;
    uint64_t outIndexToPixelAddr;
    uint numberOfRays;
} pc;

// Reorder rays
layout(local_size_x = THREADBLOCK_SIZE) in;
void main() {
    const int rayIndex = int(gl_GlobalInvocationID.x);

    IntBufferRO rayIndices = IntBufferRO(pc.rayIndexAddr);
    RayBufferRO inRays = RayBufferRO(pc.inRayAddr);
    RayBufferWO outRays = RayBufferWO(pc.outRayAddr);
    IntBufferRO inIndexToPixel   = IntBufferRO(pc.inIndexToPixelAddr);
    IntBufferWO outIndexToPixel = IntBufferWO(pc.outIndexToPixelAddr);

    if (rayIndex < pc.numberOfRays) {

        int oldRayIndex = rayIndices.data[rayIndex];
        int index = inIndexToPixel.data[oldRayIndex];
        outRays.data[rayIndex] = inRays.data[oldRayIndex];
        outIndexToPixel.data[rayIndex] = index;

    }

}
