#version 460

#extension GL_EXT_buffer_reference2 : require
#extension GL_EXT_shader_explicit_arithmetic_types_int64 : require

layout(buffer_reference, std430) buffer FlagBuffer { volatile uint data[]; };
layout(buffer_reference, std430) buffer TaskCounter { volatile uint data; };

layout(push_constant) uniform PushConstants {
	uint64_t flagBufferAddr;
	uint64_t taskCounterAddr;
	uint numBlocks;
} pc;

shared uint iBlock;

layout(local_size_x = 64) in;
void main() {
	uint localId = gl_LocalInvocationID.x;
	FlagBuffer flags = FlagBuffer(pc.flagBufferAddr);
	TaskCounter counter = TaskCounter(pc.taskCounterAddr);

	for(;;){
		if(localId == 0) {
			iBlock = atomicAdd(counter.data, 1);
		}
		barrier();

		if(iBlock >= pc.numBlocks) {
			break;
		}

		if(localId == 0){
			if(iBlock == 0) {
				atomicExchange(flags.data[iBlock], 1);
			}
			else {
				do {
					memoryBarrierBuffer();
				} while (atomicAdd(flags.data[iBlock - 1], 0) == 0);

				atomicExchange(flags.data[iBlock], 1);
			}
		}
	}
}
