#version 460

#extension GL_EXT_buffer_reference2 : require
#extension GL_EXT_shader_explicit_arithmetic_types_int64 : require

layout(buffer_reference, std430) buffer FlagBuffer { volatile uint data[]; };

layout(push_constant) uniform PushConstants {
	uint64_t flagBufferAddr;
} pc;

layout(local_size_x = 64) in;
void main() {
	uint localId = gl_LocalInvocationID.x;
	uint groupId = gl_WorkGroupID.x;
	FlagBuffer flags = FlagBuffer(pc.flagBufferAddr);

	if(localId == 0) {
		if(groupId == 0) {
			atomicExchange(flags.data[groupId], 1);
		}
		else {
			do {
				memoryBarrierBuffer();
			} while (atomicAdd(flags.data[groupId - 1], 0) == 0);

			atomicExchange(flags.data[groupId], 1);
		}
	}

}
